export const supportedLanguages = [
  { code: 'en-US', name: 'English (US)' },
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: '简体中文' },
  { code: 'zh', name: '中文' },
  { code: 'fr-FR', name: 'Français (France)' },
  { code: 'fr', name: 'Français' },
  { code: 'de-DE', name: 'Deutsch (Deutschland)' },
  { code: 'de', name: 'Deutsch' },
  { code: 'es-ES', name: 'Español (España)' },
  { code: 'es', name: 'Español' },
  { code: 'ru', name: 'Русский' },
  { code: 'ja', name: '日本語' },
  { code: 'pt-BR', name: 'Português (Brasil)' },
  { code: 'pt', name: 'Português' },
  { code: 'it', name: 'Italiano' },
  { code: 'ko', name: '한국어' },
  { code: 'ar', name: 'العربية' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'pl', name: 'Polski' },
  { code: 'sv-SE', name: 'Svenska (Sverige)' },
  { code: 'sv', name: 'Svenska' },
  { code: 'he', name: 'עברית' },
  { code: 'uk', name: 'Українська' },
  { code: 'th', name: 'ไทย' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'cs', name: 'Čeština' },
  { code: 'ro', name: 'Română' },
  { code: 'fi', name: 'Suomi' },
  { code: 'da', name: 'Dansk' },
  { code: 'hu', name: 'Magyar' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'no', name: 'Norsk' },
  { code: 'nb', name: 'Norsk bokmål' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'fa', name: 'فارسی' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'മലയാളം' },
  { code: 'mr', name: 'मराठी' },
  { code: 'ur', name: 'اردو' },
  { code: 'zh-HK', name: '繁體中文 (香港)' },
  { code: 'zh-TW', name: '繁體中文 (台灣)' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'az', name: 'Azərbaycan' },
  { code: 'eu', name: 'Euskara' },
  { code: 'bg', name: 'Български' },
  { code: 'ca', name: 'Català' },
  { code: 'et', name: 'Eesti' },
  { code: 'gl', name: 'Galego' },
  { code: 'gu', name: 'ગુજરાતી' },
  { code: 'is', name: 'Íslenska' },
  { code: 'kk', name: 'Қазақ' },
  { code: 'ky', name: 'Кыргызча' },
  { code: 'lo', name: 'ລາວ' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'mk', name: 'Македонски' },
  { code: 'mn', name: 'Монгол' },
  { code: 'ne', name: 'नेपाली' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ' },
  { code: 'si', name: 'සිංහල' },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'sq', name: 'Shqip' },
  { code: 'sr', name: 'Srpski' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'tg', name: 'Тоҷикӣ' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'uz', name: 'O\'zbek' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'am', name: 'አማርኛ' },
  { code: 'ha', name: 'Hausa' },
  { code: 'ig', name: 'Igbo' },
  { code: 'jv', name: 'Basa Jawa' },
  { code: 'km', name: 'ខ្មែរ' },
  { code: 'my', name: 'မြန်မာ' },
  { code: 'or', name: 'ଓଡ଼ିଆ' },
  { code: 'ps', name: 'پښتو' },
  { code: 'sd', name: 'سنڌي' },
  { code: 'so', name: 'Soomaali' },
  { code: 'as', name: 'অসমীয়া' },
  { code: 'bho', name: 'भोजपुरी' },
  { code: 'br', name: 'Brezhoneg' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'fy', name: 'Frysk' },
  { code: 'ga', name: 'Gaeilge' },
  { code: 'gd', name: 'Gàidhlig' },
  { code: 'mi', name: 'Te Reo Māori' },
  { code: 'mt', name: 'Malti' },
  { code: 'nn', name: 'Nynorsk' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'sa', name: 'संस्कृत' },
  { code: 'sm', name: 'Gagana Sāmoa' },
  { code: 'st', name: 'Sesotho' }
]