AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for 6180.io with Universal Links and S3 fallback

Resources:

  CloudFrontOriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: S3AccessControl-6180-v4  # Ensure this name is unique per stack
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CachingDisabledPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: 6180-CachingDisabledPolicy
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - 6180.io
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:174412649131:certificate/566b96fa-4b26-465a-bc86-2138a5c13731
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: 6180-website.s3.amazonaws.com
            OriginAccessControlId: !GetAtt CloudFrontOriginAccess.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          CachePolicyId: !Ref CachingDisabledPolicy
          Compress: false
        CacheBehaviors:
          - PathPattern: "/folder/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            CachePolicyId: !Ref CachingDisabledPolicy
            Compress: false
          - PathPattern: "/.well-known/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            CachePolicyId: !Ref CachingDisabledPolicy
            Compress: false
